export const GET_PROFILES_START = 'GET_PROFILES_START'
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS'
export const GET_PROFILES_ERROR = 'GET_PROFILES_ERROR'
export const GET_PROFILES_RESET = 'GET_PROFILES_RESET'